### ISSUE TITLE
Blank 'name' field from Restaurant search

### ISSUE THREAD

**Issue by malexander6** [rpp2205-boc-dolomite/biteshare-app#113]
@bubsinthemountains 
The `name` field comes through as blank sometimes. Seems like it is happening when I pick a restaurant with a name that starts with digits, but that could be a coincidence.  The issue can be reproduced by searching with the zip code 80516 and selecting 24 Carrot Bistro as the restaurant.

**Comment by bubsinthemountains** [comment]
fixed!
